#!/usr/bin/env python

import sys
import json

run = json.load(sys.stdin)
print "hardware: %s" % run['hw']
if run['user']:
	print "user: %s" % run['user']
print "date: %s" % run['date']
print "--"
for e in run['results']:
	r = e['result']
	if r == 100.0:
		s = "pass"
	else:
		s = "fail"
	print "%s: %s (%i%%)" % (e['name'], s, r)
