#!/usr/bin/env python

import sys
import json

import MySQLdb
from optparse import OptionParser

parser = OptionParser()
parser.add_option("-n", "--host", default="localhost")

(options, args) = parser.parse_args()

db = MySQLdb.connect(host = options.host,
		user = "test",
		db = "insanity")

c = db.cursor()

tests = json.load(sys.stdin)
for e in tests:
	c.execute("select id from tests where name='%s'" % (e['name']))
	if c.fetchone():
		continue
	c.execute("insert into tests (name) values ('%s')" % (e['name']))
