#!/usr/bin/env python

import sys
import json

import MySQLdb

db = MySQLdb.connect(host = "localhost",
		user = "test",
		db = "insanity")

c = db.cursor()

tests = json.load(sys.stdin)
for e in tests:
	c.execute("select id from tests where name='%s'" % (e['name']))
	if c.fetchone():
		continue
	c.execute("insert into tests (name) values ('%s')" % (e['name']))
